### ISSUE TITLE
Сверстать раздел "Цена"

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#127]
В рамках обновления дизайна:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F/%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-(Red)?node-id=1%3A19

Обновить блок "Цена":
<img width="937" alt="Screenshot 2021-11-25 at 00 15 02" src="https://user-images.githubusercontent.com/4641125/143319496-33fd2c9e-a89d-4f95-a51a-0562caef03b7.png">

Использовать БЭМ. Обратить внимание на мобильную версию.

Задача для @Flavissimo

**Comment by VadimCpp** [comment]
<img width="390" alt="Screenshot 2021-11-26 at 12 13 12" src="https://user-images.githubusercontent.com/4641125/143564524-df0b0352-fac7-4859-b0e5-dfabf11f05c0.png">

В задачу также есть смысл помещать то что получилось.

**Comment by alisabox** [comment]
Было бы отлично в @font-face добавить еще шрифт в формате woff2, он весит меньше и поддерживается везде (кроме IE). :)

**Comment by Flavissimo** [comment]
> Было бы отлично в @font-face добавить еще шрифт в формате woff2, он весит меньше и поддерживается везде (кроме IE). :)

Принято. Добавлю =)

**Comment by Flavissimo** [comment]
> <img alt="Screenshot 2021-11-26 at 12 13 12" width="390" src="https://user-images.githubusercontent.com/4641125/143564524-df0b0352-fac7-4859-b0e5-dfabf11f05c0.png">
> 
> В задачу также есть смысл помещать то что получилось.

Принято. Буду добавлять.
