### ISSUE TITLE
Обновить раздел "Свяжитесь с нами"

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#132]
В рамках обновления дизайна:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F

Обновить раздел "Свяжитесь с нами"
<img width="286" alt="Screenshot 2021-11-26 at 12 06 37" src="https://user-images.githubusercontent.com/4641125/143563639-60f90b5b-fb69-4704-8b2e-89a219f24001.png">

Задача для @Flavissimo

**Comment by Flavissimo** [comment]
Мобильная версия
![изображение](https://user-images.githubusercontent.com/71039087/144913713-dac09589-0ab4-4086-96dc-8dacba3b32ca.png)
1280px
![изображение](https://user-images.githubusercontent.com/71039087/144913823-39319ca6-4f3a-4249-94c1-58888a62fe4a.png)

**Comment by Flavissimo** [comment]
#147 correction Form 
1. установить form -max-width и откорректировать margin;
2.  переименовать Icon на icon.

**Comment by Flavissimo** [comment]
#147 задача закрыта и откорректирована
