### ISSUE TITLE
Обновить блок «Программа»

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#146]
Заменить блок:

<img width="724" alt="Screenshot 2021-12-06 at 18 58 43" src="https://user-images.githubusercontent.com/4641125/144888763-b30c5c5a-068f-4830-bf5a-1dd3deaa60de.png">

На блок:

<img width="956" alt="Screenshot 2021-12-06 at 18 59 41" src="https://user-images.githubusercontent.com/4641125/144888938-9bd34359-ed3f-45aa-af25-f00bba3c4c6d.png">

Дизайн тут:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F/%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-(Red)?node-id=0%3A1

**Comment by RomanRid** [comment]
#146

**Comment by RomanRid** [comment]
Возьму в работу.

**Comment by Flavissimo** [comment]
#146 убрать fluid у род. контейнера, чтобы не растягивалось по всей ширине экрана. 
![изображение](https://user-images.githubusercontent.com/71039087/146331074-cda42e7a-5039-4069-b439-28c00a7dea92.png)
