### ISSUE TITLE
Обновить блок «Результаты»

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#152]
Заменить блок:
<img width="346" alt="Screenshot 2021-12-11 at 01 10 32" src="https://user-images.githubusercontent.com/4641125/145652468-7c8dd333-3f0b-44cc-b509-b9906eb6f97b.png">

На блок:
<img width="435" alt="Screenshot 2021-12-11 at 01 11 11" src="https://user-images.githubusercontent.com/4641125/145652512-8a6374ad-8852-4944-baef-205fbd26aac8.png">

Дизайн тут:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F/%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-(Red)?node-id=0%3A1

**Comment by RomanRid** [comment]
#152 возьму в работу

**Comment by Flavissimo** [comment]
#152 убрать свойства бутстрапа и присвоить необходимые отступы в css необходимым блокам.
Убрать important!. 

602-608 
.pt-3{
  .pt-3 {
    padding-top: 1.2rem!important;
  }

671-694
@media screen and (min-width: 576px) {
  .ml-4 {
    margin-left: 38px!important;
  }
}

**Comment by VadimCpp** [comment]
> #152 убрать свойства бутстрапа и присвоить необходимые отступы в css необходимым блокам. Убрать important!.
> 
> 602-608 .pt-3{ .pt-3 { padding-top: 1.2rem!important; }
> 
> 671-694 @media screen and (min-width: 576px) { .ml-4 { margin-left: 38px!important; } }

Выполнено в другой задаче:
https://github.com/Flavissimo/Transformation/pull/159/files#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5L604

Закрываю
