### ISSUE TITLE
Обновить блок «Трек-лист» 

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#153]
Заменить блок:
<img width="364" alt="Screenshot 2021-12-11 at 01 12 56" src="https://user-images.githubusercontent.com/4641125/145652619-18d93915-fee2-4371-be3f-58a48726a66a.png">

На блок:
<img width="457" alt="Screenshot 2021-12-11 at 01 13 17" src="https://user-images.githubusercontent.com/4641125/145652628-bacd1ee0-d2b9-497d-88e2-11150919ab87.png">

Дизайн тут:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F/%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-(Red)?node-id=0%3A1

**Comment by RomanRid** [comment]
взял в работу
