### ISSUE TITLE
Обновить блок «FAQ»

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#154]
Заменить блок:
<img width="952" alt="Screenshot 2021-12-11 at 01 14 42" src="https://user-images.githubusercontent.com/4641125/145652717-1afe1ddf-6ddb-4f41-ae6c-477629955fcb.png">

На блок:
<img width="610" alt="Screenshot 2021-12-11 at 01 15 05" src="https://user-images.githubusercontent.com/4641125/145652738-f3bbf9d1-c92f-4aea-bdcf-ac80bf795bd8.png">

Дизайн тут:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F/%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-(Red)?node-id=0%3A1

**Comment by RomanRid** [comment]
#154 возьму в работу

**Comment by VadimCpp** [comment]
<img width="1329" alt="Screenshot 2022-01-06 at 17 09 09" src="https://user-images.githubusercontent.com/4641125/148395444-7fa0de45-f79b-4285-9cf1-33b040c08e4a.png">

Задача завершена
