### ISSUE TITLE
Обновить блок «О проекте» 

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#155]
Заменить блок:
<img width="354" alt="Screenshot 2021-12-11 at 01 21 30" src="https://user-images.githubusercontent.com/4641125/145653150-bd0718e0-8b8e-4325-8056-7e5f75a8656b.png">

На блок:
<img width="638" alt="Screenshot 2021-12-11 at 01 21 58" src="https://user-images.githubusercontent.com/4641125/145653171-ea74c4b9-ae10-448d-b8d9-9269c7c6c6c6.png">

Дизайн тут:
https://www.figma.com/file/BREOCSY1KO8hayc6jNUr4F/%D0%9F%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-(Red)?node-id=0%3A1

**Comment by RomanRid** [comment]
#155 возьму в работу
