### ISSUE TITLE
Изменить стоимость участия марафона

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#176]
Установить стоимость - 2000 рублей
<img width="409" alt="Screenshot 2022-02-10 at 13 01 50" src="https://user-images.githubusercontent.com/4641125/153394027-c51eab59-b8e2-4695-8c20-e3085aef6239.png">

Код, который закомментирован (изменение цены по датам), не трогать.

**Comment by anna-popova** [comment]
в работе
