### ISSUE TITLE
Улучшить editorconfig

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#185]
В файле `.editorconfig` ничего не сказано про файлы html.

По умолчанию для всех файлов используются символы tab:
```
[*]
indent_style = tab
```

В рамках этой задачи добавить по умолчанию для всех файлов:
```
indent_style = space
indent_size = 2
```

И убрать дублирующиеся настройки для yml, js, css

**Comment by anna-popova** [comment]
взяла в работу
