### ISSUE TITLE
Улучшить БЭМ блока "Программа"

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#186]
Вод код:
```
 <section id="programme" class="section-programme">
      <div class="container">
        <h2 class="container section-header">Программа</h2>
        <p class="container section-text">
          На протяжении четырёх недель будем говорить и действовать&#58;
        </p>
        <div class="programme__content">
          <ol class="list-group">
            <li class="list__group-icon section-text">Соблюдать режим дня...</li>
            ...
          </ol>
          <div class="programme__content-img">
            <img src="image/programme__img.jpg" alt="">
          </div>
        </div>
		  <div class="programme__webinars webinars">
			  <h3 class="container webinars__title">Список вебинаров:</h3>
			  <ul class="webinars-list">
				  <li class="webinars-item section-text">....ез вредных привычек (Анна Граб)</li>
                                     ...
			  </ul>
		  </div>
      </div>
    </section>
```

Выглядит этот код так:

<img width="1021" alt="Screenshot 2022-02-16 at 21 57 15" src="https://user-images.githubusercontent.com/4641125/154336310-415a17cf-3220-4875-96f9-31edb327cb92.png">

Сейчас там классы наименование не соответствует БЭМ:
- section-programme
- container
- section-header
- section-text
- programme__content
- list-group
- list__group-icon
- programme__content-img
- programme__webinars
- webinars
- webinars__title
- webinars-list
- webinars-item

Бррр 🙂

Прошу исследовать раздел сайта "О проекте", там два БЭМ блока:
- about
- about__header
- about__text
- about__text--space
- about__cards
- information-card
- information-card__image-wrap
- information-card__text-wrap
- information-card__title
- information-card__description

В этой задаче прошу реализовать классы по БЭМ для раздела "программа"

**Comment by anna-popova** [comment]
беру в работу
