### ISSUE TITLE
Улучшить отступы и косметические исправления

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#188]
Недавно в чате https://t.me/frontendbasics выяснили, что большие отступы выглядят привлекательнее. Вот пример, раздел "Новости":
<img width="188" alt="Screenshot 2022-02-19 at 12 32 35" src="https://user-images.githubusercontent.com/4641125/154795272-d42fa536-7653-4dd1-bbf8-07cefab93ae7.png">

1. В блоке "Новости" пока еще используется класс container , который позаимствован у bootstrap и от которого мы скоро избавимся. Там такие отступы:
```
padding-right: 15px;
padding-left: 15px;
```

Но так как container в блоке "Новости" засунут аж 2 раза, то общий отступ (и этот отступ пользователям нравится:
```
padding-right: 30px;
padding-left: 30px;
```

Необходимо реализовать двойной отступ для блоков "О проекте" и "Программа" для мобильной версии сайта

2. Мелкие правки

В файле style.css разное форматирование в разных частях, например, в части:

```
/* Блок about - Раздел сайта "О проекте" */
```
Между блоками отступ 2 строки, а между классами - 1 строка

В части:
```
/* блок Список вебинаров - Раздел сайта "Программа" */
```

Между классами нет отступа. 

Прошу между классами сделать отступ 1 строку

3. Класс элемента programme__webinars относится к блоку programme. Прошу в файле style.css перенести класс к другим классам блока programme

**Comment by anna-popova** [comment]
в работе
