### ISSUE TITLE
Улучшить раздел "Новости"

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#190]
Реализовать БЭМ для раздела "Новости" по аналогии с разделами сайта "О проекте" и "Программа"

Задача для @anna-popova

**Comment by VadimCpp** [comment]
Для раздела "Новости" использовать универсальное наименование классов, чтобы потом их использовать с разделами сайта "О проекте" и "Программа".

Пример: 
- chapter
- chapter__title
- chapter__text

Или:
- section
- section__title
- section__text

**Comment by anna-popova** [comment]
в работе
