### ISSUE TITLE
Добавить заглушку

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#2]
Вставить в body код:
```
<p>Добро пожаловать в преображение. Сайт разрабатывается...</p>
```

**Comment by Flavissimo** [comment]
Готово.

**Comment by VadimCpp** [comment]
@Flavissimo скиньте в задачу ссылку на коммит

**Comment by Flavissimo** [comment]
#2 add plug

**Comment by VadimCpp** [comment]
Заглушка в одном из этих коммитов:

<img width="581" alt="Screenshot 2020-12-06 at 12 42 32" src="https://user-images.githubusercontent.com/4641125/101277934-8506dc80-37c0-11eb-965b-a9a891d16c66.png">
