### ISSUE TITLE
Подключить Bootstrap

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#3]
Скопировать на свой сайт в head строки 8-9:
https://github.com/VadimCpp/club111-landing/blob/master/index.html#L8

Скопировать на свой сайт в конец body строки 351-353:
https://github.com/VadimCpp/club111-landing/blob/master/index.html#L351

Затем вставить код:
```
<div class="container container-center">
  И тут текст, чтобы посмотреть как работает класс контейнер на разных размерах экрана
</div>
```

**Comment by Flavissimo** [comment]
Готово.

**Comment by VadimCpp** [comment]
@Flavissimo скиньте в задачу ссылку на коммит

**Comment by Flavissimo** [comment]
#3 add Bootstrap

**Comment by VadimCpp** [comment]
https://github.com/Flavissimo/Transformation/commit/cf9ba29fd0ad571f827253a3d523348c344a5edf
