### ISSUE TITLE
Изменить раздел "Результаты"

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#32]
Задача для @Flavissimo .

Убрать из галереи данные и компонент прокрутки и оставить только фотографию с описанием: 
<img width="285" alt="Screenshot 2020-12-19 at 12 03 38" src="https://user-images.githubusercontent.com/4641125/102686753-56dac100-41f2-11eb-90c9-d0d95cc91f27.png">

Сделать контейнер на всю ширину экрана красным цветом.

**Comment by ASinyukhin** [comment]
Данными являются чёрный текст?

**Comment by VadimCpp** [comment]
@ASinyukhin карусель не нужна, прошу ее просто убрать

**Comment by VadimCpp** [comment]
@Flavissimo а где коммиты к этой задаче?
