### ISSUE TITLE
Указать метатеги

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#53]
Установить метатеги в head:
```
<meta property="og:title" content="Преображение" />
<meta property="og:description" content="Твоё спасение на самоизоляции" />
<meta property="og:image" content="//image/preview.jpg" />
```

**Comment by VadimCpp** [comment]
![photo_2020-12-28 17 23 33](https://user-images.githubusercontent.com/4641125/103224986-8e074b80-4931-11eb-8cd4-0a1e743b9040.jpeg)

**Comment by Flavissimo** [comment]
Первые два коммита удалены с помощью: 1.git reset --hard номер стр.; 2. git push --force-with-lease origin ветка.

**Comment by VadimCpp** [comment]
Прорерил, закрываю.
