### ISSUE TITLE
Обновить дату Марафона

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#78]
Задача для @Kislax 

Установить информацию на сайт:
```
Преображение 5. 0 пройдет с 2 по 22 февраля и будет иметь  большой всероссийский масштаб. Чат в телеграмм только на этот проект.
```

**Comment by Kislax** [comment]
расположение информации где должно быть? 
 в шапке? отдельный контрастный блок под новость?

**Comment by VadimCpp** [comment]
Информацию поместить в блок "Цена":
<img width="596" alt="Screenshot 2021-01-27 at 14 12 11" src="https://user-images.githubusercontent.com/4641125/105989365-ae016a80-60a9-11eb-9bbf-a39fd8c294ee.png">
