### ISSUE TITLE
Указать цену в разделе 

### ISSUE THREAD

**Issue by VadimCpp** [Flavissimo/Transformation#85]
В конце раздела "Цена" указать информацию:

```
Стоимость участия: 500 руб. + один продукт для здоровья линейки Вэлнэс.
Заказ продукта Велнес осуществить тут ➡️ https://vk.com/id14100821
``` 

Ссылка должна открываться в текущем окне.

**Comment by Kislax** [comment]
Переход должен произойти при нажатии на кнопку "тут"? 
Или адрес ссылки должен присутствовать в тексте?
